### ISSUE TITLE
быстродействие

### ISSUE THREAD

**Issue by kuzmichevdima** [DimaProskurin/Markov-Chains#13]
https://github.com/DimaProskurin/Markov-Chains/blob/87e8d889db9a92ffb9c38d04944f290254003f1e/generate.py#L36-L38

https://github.com/DimaProskurin/Markov-Chains/blob/87e8d889db9a92ffb9c38d04944f290254003f1e/generate.py#L52-L53

почему бы не хранить слова в текущем предложении в виде списка? Текущий способ хуже тем, что 1) дописывать каждый раз слово долго, потому что строка immutable и копируется при операции += 2) приходится дополнительно поддерживать current_words_in_sentence

**Comment by DimaProskurin** [comment]
Исправлено
