### ISSUE TITLE
крайний случай

### ISSUE THREAD

**Issue by kuzmichevdima** [DimaProskurin/Markov-Chains#14]
https://github.com/DimaProskurin/Markov-Chains/blob/87e8d889db9a92ffb9c38d04944f290254003f1e/generate.py#L41
https://github.com/DimaProskurin/Markov-Chains/blob/87e8d889db9a92ffb9c38d04944f290254003f1e/generate.py#L46

что, если seed отсутствует среди известных слов? Здесь будет exception

**Comment by DimaProskurin** [comment]
Исправлено
