### ISSUE TITLE
проверка слова

### ISSUE THREAD

**Issue by kuzmichevdima** [DimaProskurin/Markov-Chains#16]
https://github.com/DimaProskurin/Markov-Chains/blob/43463fb7dd8eb88358738f666effcfcac21328c1/generate.py#L49-L50

зачем брать keys() и преобразовывать к list? Можно просто писать current_word not in dictionary

**Comment by kuzmichevdima** [comment]
Экспериментально я проверил, что проверки вида "x in d.keys()" работают в 3-4 раза медленнее, чем "x in d"

**Comment by DimaProskurin** [comment]
Исправлено
