### ISSUE TITLE
аргументы

### ISSUE THREAD

**Issue by kuzmichevdima** [DimaProskurin/Markov-Chains#3]
https://github.com/DimaProskurin/Markov-Chains/blob/a9d5045ee31bb4b7bf60eb2ae3eac1e301c135f8/generate.py#L11-L15

зачем  vars(parser.parse_args())?
далее, не нужно присваивать в новые переменные аргументы, обращайся прямо к ним: args.model, args.length и так далее

**Comment by DimaProskurin** [comment]
vars(parser.parse_args()) нужен чтобы создать словарь с аргументами. По другому к ним не получается обратиться (так args.model не понимает). Я убрал ненужные присваивания в новые переменные, теперь всё происходит с переменными из словаря

**Comment by kuzmichevdima** [comment]
Что значит "args.model не понимает"? Так совершенно точно работает. Вот минимальный пример, на котором можно в этом убедиться:

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--arg')
args = parser.parse_args()
print(args.arg)

python3 tmp.py --arg qwe
qwe
