### ISSUE TITLE
рандом

### ISSUE THREAD

**Issue by kuzmichevdima** [DimaProskurin/Markov-Chains#5]
https://github.com/DimaProskurin/Markov-Chains/blob/a9d5045ee31bb4b7bf60eb2ae3eac1e301c135f8/generate.py#L34-L38

давай использовать numpy.random.choice с параметром p (посмотри документацию, там все просто). В этом случае нам не нужно копировать очередное слово count раз (это засоряет память без нужды).

**Comment by DimaProskurin** [comment]
Сделано
