### ISSUE TITLE
if __name__ == "__main__"

### ISSUE THREAD

**Issue by kuzmichevdima** [DimaProskurin/Markov-Chains#9]

**Comment by kuzmichevdima** [comment]
https://github.com/DimaProskurin/Markov-Chains/blob/87e8d889db9a92ffb9c38d04944f290254003f1e/train.py#L68-L76

вот этот код всегда выполняется и не попадает в if

**Comment by kuzmichevdima** [comment]
https://github.com/DimaProskurin/Markov-Chains/blob/87e8d889db9a92ffb9c38d04944f290254003f1e/train.py#L8

https://github.com/DimaProskurin/Markov-Chains/blob/87e8d889db9a92ffb9c38d04944f290254003f1e/train.py#L78

и почему этих ифа два?

**Comment by DimaProskurin** [comment]
Исправлено
